name: Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Poetry
      run: >-
        pip install poetry --user

    - name: Build and Publish Release
      run: >- 
        poetry build

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.tag }}
        release_name: Release ${{ steps.get_version.outputs.tag }}
        body: |
          Release ${{ steps.get_version.outputs.tag }}

          Changes:
          - Describe your changes here

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/*
        asset_name: jobspy-fork-${{ steps.get_version.outputs.tag }}.tar.gz
        asset_content_type: application/x-gzip
